sudo: required
services:
        - docker
before_install:
        - docker build -t patelkhushbu09/docker-react -f Dockerfile.dev .
script:
        - docker run -e CI=true patelkhushbu09/docker-react npm run test
